### ISSUE TITLE
Any plans to make this work for React Native?

### ISSUE THREAD

**Issue by t2** [rt2zz/unstated-persist#1]

**Comment by rt2zz** [comment]
rn is supported, just need to pass AsyncStorage into the persist config instead of localForage: https://github.com/rt2zz/unstated-persist#usage

**Comment by t2** [comment]
@rt2zz You're right, I got lazy. The `babel-preset-flow` and `babel-preset-env` dependencies needed to be installed. Should these be in your `dependencies` rather than `devDependencies`? The `.babelrc.js` is expecting them.

**Comment by rt2zz** [comment]
ah hmm, probably we should not include babelrc in the bundle, I think that was an oversight

**Comment by t2** [comment]
Those were my thoughts too I just didn't know if you had another reason.

**Comment by rt2zz** [comment]
updated in v0.0.3

**Comment by fukhaos** [comment]
@t2 Could you provide how you use AsyncStorage with unstated-persist ?

**Comment by joaovpmamede** [comment]
@fukhaos something like:
```
export default class MyContainer extends PersistContainer {
  state = {
    // my state
  };

  persist = {
    key: 'myContainer',
    version: 1,
    storage: AsyncStorage
  };
}
```
